### ISSUE TITLE
MVP: Creating a glossary for learners and translators

### ISSUE THREAD

**Issue by contraexemplo** [infuse-l10n-pt-br/Infuse#24]
### English description

I'll start by saying that [Kubernetes does it in a more elegant way](https://kubernetes.io/docs/reference/glossary/?fundamental=true) we can always replicate 1:1 later on; my goal is to work towards a minimum viable page that learners, mentors, and the overall Infuse community can work with to build a common vocabulary.

I made this concept with Markdown links and headings to somewhat replicate the Kubernetes' example.

<img width="1197" alt="Screenshot of a glossary page with links with the alphabet and the beginning of a glossary with the concepts of Attacker and Sandboxed environment" src="https://github.com/user-attachments/assets/272f9383-e434-46ec-bd05-8ec1abd9a92d">

So...

What do you think? 👀 

***

### Descrição em português 🇧🇷

Começo dizendo que [Kubernetes faz a mesma coisa de um jeito mais elegante](https://kubernetes.io/docs/reference/glossary/?fundamental=true) que nós podemos replicar 1:1 no futuro; o meu objetivo é trabalhar em uma página minimamente viável com a qual estudantes, mentores, e toda a comunidade Infuse possam construir um vocabulário em comum.

Fiz esse conceito com links e cabeçalhos Markdown simples para replicar o formato do Kubernetes.

<img width="1197" alt="Captura de tela do meu navegador mostrando uma página de nome Glossário. Nela, temos links com as letras do alfabeto e começo de um glossário com conceitos de Atacante e Ambiente isolado." src="https://github.com/user-attachments/assets/272f9383-e434-46ec-bd05-8ec1abd9a92d">

Então...

O que vocês acham? 👀

**Comment by contraexemplo** [comment]
(Fixed that awkward no Git info message with fe088c5f155f717921b0105351447b88c6561acc, by the way.)

**Comment by yamakat** [comment]
So beautiful! I think it looks and works out great, and it's going to be very helpful.
