### ISSUE TITLE
Brazilian Portuguese translation of the Malicious Infrastructure learning path

### ISSUE THREAD

**Issue by contraexemplo** [infuse-l10n-pt-br/Infuse#4]
Learning path modules can be found under `content/learning-path/`. We need to create the following files to successfully translate the Malicious Infrastructure learning path into Brazilian Portuguese:

```
content/
├── learning-path/
|          ├── _index.pt-br.md
|          └── 1/
|            ├── _index.pt-br.md
|            ├── introduction.pt-br.md
|            ├── module-1.pt-br.md
|            ├── module-2.pt-br.md
|            ├── module-3.pt-br.md
|            ├── module-4.pt-br.md
|            ├── module-5.pt-br.md
|            ├── module-6.pt-br.md
|            ├── module-7.pt-br.md
|            ├── module-8.pt-br.md
|            ├── module-9.pt-br.md
│            └── module-10.pt-br.md
```

### Content to be translated

- [x] Introduction
- [x] Module 1
- [x] Module 2
- [x] Module 3
- [x] Module 4
- [x] Module 5
- [x] Module 6
- [x] Module 7
- [x] Module 8
- [x] Module 9
- [x] Module 10

**Comment by contraexemplo** [comment]
@yamakat Let me know what are your preferred modules to translate! I have no preferences, but I'd like us to work together on a few details about **Module 10** (Capture-the-flag exercise) as it involves assets that need some accessibility improvements.

**Comment by yamakat** [comment]
Ok! & I'm working on `introduction.pt-br.md` right now.

**Comment by contraexemplo** [comment]
**Our Brazilian Portuguese translation won't show up without all the other pages, so I've been focusing on that this week.** I'm almost fully finished with testing i18n keys and creating meta pages (to fully complete #3).

**Comment by contraexemplo** [comment]
Commit f749e2151d111699289f967c01f8e888caa39519 will help you test an interface localized to Brazilian Portuguese for the website. 🎉

**Comment by contraexemplo** [comment]
The badge for the Malicious Infrastructure has a fun alliteration (Infrastructure Inspector) that I can only preserve if I use a gendered translation (e.g. "Inspetor", "Inspetora"). Any thoughts on what should be our strategy for that?

**Comment by yamakat** [comment]
> The badge for the Malicious Infrastructure has a fun alliteration (Infrastructure Inspector) that I can only preserve if I use a gendered translation (e.g. "Inspetor", "Inspetora"). Any thoughts on what should be our strategy for that?

That's a good one. Maybe "Fiscal de Infraestrutura"?

**Comment by yamakat** [comment]
Mmmh I think "Investigante de Infraestrutura" goes pretty well together!!

**Comment by contraexemplo** [comment]
**All modules were merged into `main`.** I want us to take a second look at each module now that they can be rendered locally. Follow the following instructions to do so:

0. Make sure you're on the `main` branch
1. Run `hugo server` on the root directory
2. Go to `localhost` address
3. Select **Brazilian Portuguese** on the language menu
4. Read all modules, now rendered with Hugo ✨
